povilo_servisas/autoservisas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('my_cars/', views.UserCarListView.as_view(), name='my_cars'),
    path('', views.index, name='index'),
    path('brands/', views.brands, name='brands'),
    path('brands/<str:brand>/', views.brand_detail, name='brand_detail'),
    path('car/<int:car_id>/service-orders/', views.CarServiceOrderListView.as_view(), name='car_service_orders'),
    path('user_car_list/', views.UserCarListView.as_view(), name='user_car_list'),
    path('parts-and-services/', views.PartServiceListView.as_view(), name='parts_and_services'),
    path('parts-and-services/<int:pk>/', views.PartServiceDetailView.as_view(), name='partservice_detail'),
    path('review/create/', views.review_create, name='review_create'),
    path('place_order/<int:car_id>/', views.PlaceOrderView.as_view(), name='place_order'),
    path('cancel_order/<int:order_id>/', views.CancelOrderView.as_view(), name='cancel_order'),
    path('add_car/', views.add_car, name='add_car'),

]

povilo_servisas/povilo_servisas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autoservisas.urls')),
    path('user/', include('user_profile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/translations', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]+ (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

povilo_servisas/autoservisas/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _ 
from django.urls import reverse
from tinymce.models import HTMLField


User = get_user_model()


class CarModel(models.Model):

    make = models.CharField(_("make"), max_length=100, db_index=True)
    model = models.CharField(_("model"), max_length=100, db_index=True)
    year = models.IntegerField(_("year"), db_index=True)

    class Meta:
        verbose_name = _("car model")
        verbose_name_plural = _("car models")
        ordering = ["make", "model", "year"]

    def __str__(self):
        return f"{self.make} {self.model} {self.year}"

    def get_absolute_url(self):
        return reverse("carmodel_detail", kwargs={"pk": self.pk})
    

class Car(models.Model):
    car_model = models.ForeignKey(
        CarModel,
        verbose_name=_("car model"),
        on_delete=models.CASCADE,
        related_name="cars",
    )
    plate = models.CharField(_("plate"), max_length=50, null=True, blank=True, db_index=True)
    vin = models.CharField(_("vin"), max_length=17, null=True, blank=True, db_index=True)
    color = models.CharField(_("color"), max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = _("car")
        verbose_name_plural = _("cars")

    def __str__(self):
        return f"{self.owner}: {self.car_model} - {self.plate}"

    def get_absolute_url(self):
        return reverse("car_detail", kwargs={"pk": self.pk})
    
    owner = models.ForeignKey(
        User, 
        verbose_name=_("owner"), 
        on_delete=models.CASCADE,
        null=True, blank=True,
    )

SERVICEORDER_STATUS = (
    (0, _("confirmed")),
    (1, _("processing")),
    (2, _("completed")),
    (3, _("cancelled")),
)

class ServiceOrder(models.Model):
    car = models.ForeignKey(
        Car,
        verbose_name=_("car"), 
        on_delete=models.CASCADE
    )
    date = models.DateField(_("date"), auto_now=False, auto_now_add=True)
    status = models.PositiveSmallIntegerField(
        _("status"), choices=SERVICEORDER_STATUS, default=0
    )

    class Meta:
        verbose_name = _("service order")
        verbose_name_plural = _("service orders")

    def __str__(self):
        return f"{self.date} - {self.car} - {self.status}"

    def get_absolute_url(self):
        return reverse("serviceorder_detail", kwargs={"pk": self.pk})


class PartService(models.Model):
    name = models.CharField(_("name"), max_length=50, db_index=True)
    price = models.DecimalField(_("price"), max_digits=10, decimal_places=2)
    details = HTMLField(_("details"), blank=True, null=True)

    class Meta:
        verbose_name = _("part or service")
        verbose_name_plural = _("parts and services")

    def __str__(self):
        return f" {self.name} {self.price}"

    def get_absolute_url(self):
        return reverse("partservice_detail", kwargs={"pk": self.pk})


class OrderLine(models.Model):
    order = models.ForeignKey(
        ServiceOrder, 
        verbose_name=_("order"), 
        on_delete=models.CASCADE,
        related_name="lines",
        db_index=True,
        null=False,
        )
    part_service = models.ForeignKey(
        PartService, 
        verbose_name=_("part service id"), 
        on_delete=models.CASCADE,
        related_name="lines",
        null=False,
        )
    quantity = models.IntegerField(_("quantity"), default=1)
    price = models.DecimalField(_("price"), max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = _("order line")
        verbose_name_plural = _("order lines")
        ordering = ["order"]

    def __str__(self):
        return f"{self.order} - {self.part_service} - {self.quantity} - {self.price}"

    def get_absolute_url(self):
        return reverse("orderline_detail", kwargs={"pk": self.pk})


class PartServiceReview(models.Model):
    partservice = models.ForeignKey(
        PartService,
        verbose_name=_("part or service"),
        on_delete=models.CASCADE,
        related_name='reviews',
    )
    reviewer = models.ForeignKey(
        User,
        verbose_name=_("reviewer"),
        on_delete=models.CASCADE,
        related_name='part_service_reviews',
    )
    content = models.TextField(_("Content"), max_length=4000)
    created_at = models.DateTimeField(
        _("created at"),
        auto_now_add=True,
        db_index=True,
    )

    class Meta:
        verbose_name = _("part or service review")
        verbose_name_plural = _("part or service reviews")
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.partservice} review by {self.reviewer}"

    def get_absolute_url(self):
        return reverse("partservicereview_detail", kwargs={"pk": self.pk})

povilo_servisas/autoservisas/forms.py
from django import forms
from . import models

class BrandSearchForm(forms.Form):
    search_query = forms.CharField(label='Search', required=False)


class PartServiceReviewForm(forms.ModelForm):
    class Meta:
        model = models.PartServiceReview
        fields = ('content', 'partservice')
        widgets = {
            'partservice': forms.HiddenInput(),
        }
        labels = {
            'content': '',
        }


class OrderForm(forms.Form):
    part_service = forms.ModelChoiceField(
        queryset=models.PartService.objects.all(),
        label="Select Part or Service",
    )
    quantity = forms.IntegerField(min_value=1, label="Quantity", initial=1)


class CarCreationForm(forms.ModelForm):
    make = forms.CharField(label="Make", max_length=100)
    model = forms.CharField(label="Model", max_length=100)
    year = forms.IntegerField(label="Year")

    class Meta:
        model = models.Car
        fields = ['make', 'model', 'year', 'plate', 'vin', 'color']

povilo_servisas/autoservisas/views.py
from typing import Any
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.urls import reverse
from . import models, forms
from .forms import BrandSearchForm


class PlaceOrderView(generic.edit.FormView):
    template_name = 'autoservisas/order_form.html'
    form_class = forms.OrderForm

    def form_valid(self, form):
        car_id = self.kwargs['car_id']
        car = get_object_or_404(models.Car, pk=car_id)
        part_service = form.cleaned_data['part_service']
        quantity = form.cleaned_data['quantity']
        cancel_order = form.cleaned_data.get('cancel_order')

        if cancel_order:
            service_order = models.ServiceOrder.objects.create(
                car=car, status=3 
            )
            messages.success(self.request, 'Order canceled successfully.')
        else:
            service_order = models.ServiceOrder.objects.create(car=car)

            models.OrderLine.objects.create(
                order=service_order,
                part_service=part_service,
                quantity=quantity,
                price=part_service.price * quantity,
            )

            messages.success(self.request, 'Order placed successfully.')

        return redirect('user_car_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['car_id'] = self.kwargs['car_id']
        return context


class CancelOrderView(generic.View):
    def get(self, request, order_id):
        order = get_object_or_404(models.ServiceOrder, pk=order_id)
        if order.status == 0:
            order.status = 3
            order.save()
            messages.success(request, 'Order canceled successfully.')
        else:
            messages.error(request, 'Cannot cancel this order.')
        return redirect('car_service_orders', car_id=order.car.id)


class UserCarListView(LoginRequiredMixin, generic.ListView):
    model = models.Car
    template_name = "autoservisas/user_car_list.html"
    paginate_by = 5

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset
    

class CarServiceOrderListView(generic.ListView):
    model = models.ServiceOrder
    template_name = 'autoservisas/serviceorder_list.html'
    context_object_name = 'service_orders'

    def get_queryset(self):
        car = get_object_or_404(models.Car, pk=self.kwargs['car_id'])
        return models.ServiceOrder.objects.filter(car=car)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = get_object_or_404(models.Car, pk=self.kwargs['car_id'])
        context['car'] = car
        return context
    

def index(request:HttpRequest):
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits +1
    context = {
        "num_cars": models.Car.objects.count(),
        "num_makes": models.CarModel.objects.values("make").distinct().count(),
        "num_orders": models.OrderLine.objects.count(),
        "parts_services": models.PartService.objects.all(),
        "num_visits": num_visits,
    }
    return render(request, "autoservisas/index.html", context)


def brands(request:HttpRequest):
    search_query = request.GET.get("search_query")
    if request.GET.get("reset_search"):
        return redirect("brands")
    if search_query:
        car_models = models.CarModel.objects.filter(make__icontains=search_query)
    else:
        car_models = models.CarModel.objects.all()
    unique_brands = sorted(set(model.make for model in car_models))
    page_number = request.GET.get("page")
    items_per_page = 3
    paginator = Paginator(unique_brands, items_per_page)
    page_obj = paginator.get_page(page_number)

    search_form = BrandSearchForm(initial={"search_query": search_query})

    return render(
        request,
        "autoservisas/brand_list.html",
        {"brand_list": page_obj, "search_form": search_form},
    )

def brand_detail(request:HttpRequest, brand):
    car_models = models.CarModel.objects.filter(make=brand)
    return render(
        request,
        "autoservisas/brand_detail.html",
        {"brand": brand, "car_models": car_models},
    )


def orders(request:HttpRequest):
    return render(
        request,
        "autoservisas/order_list.html",
        {"order_list": models.OrderLine.objects.all()}
        )


class PartServiceListView(generic.ListView):
    model = models.PartService
    template_name = 'autoservisas/partservice_list.html'
    context_object_name = 'partsandervices'

    def get_queryset(self):
        return models.PartService.objects.all().order_by('name')
    

class PartServiceDetailView(generic.edit.FormMixin, generic.DetailView):
    model = models.PartService
    template_name = 'autoservisas/partservice_detail.html'
    context_object_name = 'partservice'
    form_class = forms.PartServiceReviewForm

    def get_initial(self):
        initial = super().get_initial()
        initial['partservice'] = self.get_object()
        initial['reviewer'] = self.request.user
        return initial

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.partservice = self.object
        form.instance.reviewer = self.request.user
        form.save()
        messages.success(self.request, 'Review posted successfully.')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('partservice_detail', kwargs={'pk': self.object.pk})
    
def review_create(request: HttpRequest):
    if request.method == 'POST':
        form = forms.PartServiceReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.reviewer = request.user
            review.save()
            messages.success(request, 'Review posted successfully.')
            return redirect('partservice_detail', pk=review.partservice.pk)
    else:
        form = forms.PartServiceReviewForm()

    return render(request, 'partservice_review_create.html', {'form': form})


def add_car(request):
    if request.method == 'POST':
        form = forms.CarCreationForm(request.POST)
        if form.is_valid():
            car_model, created = models.CarModel.objects.get_or_create(
                make=form.cleaned_data['make'],
                model=form.cleaned_data['model'],
                year=form.cleaned_data['year']
            )
            new_car = models.Car(
                car_model=car_model,
                plate=form.cleaned_data['plate'],
                vin=form.cleaned_data['vin'],
                color=form.cleaned_data['color'],
                owner=request.user
            )
            new_car.save()

            return redirect('my_cars')
    else:
        form = forms.CarCreationForm()

    return render(request, 'autoservisas/add_car.html', {'form': form})

povilo_servisas/autoservisas/templates/autoservisas/add_car.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "add a car"|title %}{% endblock title %}
{% block content %}
<h1>{% trans "add a car"|capfirst %}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% trans "add car"|capfirst %}</button>
    <a href="{% url 'user_car_list' %}" class="btn btn-secondary cancel-button">{% trans "cancel"|capfirst %}</a>
</form>
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/brand_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "car models for"|capfirst %} {{ brand }}{% endblock title %}
{% block content %}
<h1>{% trans "car models for"|capfirst %} {{ brand }}</h1>
{% if car_models %}
    <table class="car-model-table">
        <thead>
            <tr>
                <th>{% trans "model"|capfirst %}</th>
                <th>{% trans "year"|capfirst %}</th>
            </tr>
        </thead>
        <tbody>
            {% for car_model in car_models %}
                <tr>
                    <td>{{ car_model.model }}</td>
                    <td>{{ car_model.year }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>{% trans "no car models found for"|capfirst %} {{ brand }}.</p>
{% endif %}
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/brand_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "brands in"|title %} {{ block.super }}{% endblock title %}
{% block content %}
<h1>{% trans "car brands"|capfirst %}</h1>

<form method="get" action="">
    {{ search_form.as_p }}
    <button type="submit" class="search-button">{% trans "search"|capfirst %}</button>
    <a href="?reset_search" class="reset-button">{% trans "reset"|capfirst %}</a>
</form>

{% if brand_list %}
    {% with brand_list as page_obj%}
        {% include "autoservisas/inc/pager_prev_next.html" %}
    {% endwith %}
    <ul class="brand-list">
        {% for brand in brand_list %}
            <li><a href="{% url 'brand_detail' brand %}">{{ brand }}</a></li>
        {% endfor %}
    </ul>
    {% with brand_list as page_obj %}
        {% include "autoservisas/inc/pager_pages.html" %}
    {% endwith %}
{% endif %}
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Welcome to"|capfirst %} {{block.super}}{% endblock title %}
{% block content %}
    <h1>"{% trans "welcome to"|capfirst %} Povilo Servisas PTU16"</h1>
    <p>{% trans "Current Database Status"|capfirst %}:</p>
    <ul>
        <li>{% trans "cars"|capfirst %}: {{ num_cars }}</li>
        <li>{% trans "brands"|capfirst %}: {{ num_makes }}</li>
        <li>{% trans "orders currently"|capfirst %}: {{ num_orders }}</li>
        <li>{% trans "your visits"|capfirst %}: {{ num_visits }}</li>
    </ul>
{% endblock content%}

povilo_servisas/autoservisas/templates/autoservisas/order_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "place order"|title %}{% endblock title %}
{% block content %}
<div class="container">
    <h1>{% trans "place order"|capfirst %}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button type="submit">{% trans "place order"|capfirst %}</button>
            <button type="button" onclick="window.location.href = '{% url 'user_car_list' %}';" class="btn btn-danger">{% trans "cancel order"|capfirst %}</button>
        </div>
    </form>
</div>
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/partservice_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "part or service detail"|title %}{% endblock title %}

{% block content %}
<div class="container">
    <h1>{% trans "part or service detail"|capfirst %}</h1>
    <p>{% trans "name"|capfirst %}: {{ partservice.name }}</p>
    <p>{% trans "price"|capfirst %}: ${{ partservice.price }}</p>
    <div>{% trans "details"|capfirst %}: {{ partservice.details|safe }}</div>

    <h2>{% trans "reviews"|capfirst %}</h2>
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'review_create' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button type="submit">{% trans "post review"|capfirst %}</button></p>
    </form>
    {% else %}
    <p>{% trans "login to post a review"|capfirst %}.</p>
    {% endif %}
    
    {% if partservice.reviews.all %}
    <ul class="cool-list">
        {% for review in partservice.reviews.all %}
            <li>
                <h4>
                    <span>{{ review.reviewer }}</span>
                    <span class="float-right">{{ review.created_at }}</span>
                </h4>
                {{ review.content }}
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>{% trans "no reviews yet"|capfirst %}.</p>
    {% endif %}
</div>
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/partservice_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "parts and services"|title %}{% endblock title %}

{% block content %}
<div class="part-service-list">
    <h1>{% trans "parts and services"|capfirst %}</h1>
    <ul>
        {% for partservice in partsandervices %}
            <li>
                <a href="{% url 'partservice_detail' pk=partservice.pk %}">
                    {{ partservice.name }}
                </a>
            </li>
        {% empty %}
            <p>{% trans "no parts or services available"|capfirst %}.</p>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/serviceorder_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "service orders for"|title %} {{ car.car_model }}{% endblock title %}
{% block content %}
<h1>{% trans "orders for"|capfirst %} {{ car.car_model }}</h1>
{% if service_orders %}
    <table class="car-model-table">
        <tr>
            <th>{% trans "date"|capfirst %}</th>
            <th>{% trans "status"|capfirst %}</th>
            <th>{% trans "part"|capfirst %} / {% trans "service"|capfirst %}</th>
            <th>{% trans "quantity"|capfirst %}</th>
            <th>{% trans "price"|capfirst %}</th>
            <th>{% trans "action"|capfirst %}</th>
        </tr>
        {% for order in service_orders %}
        <tr>
            <td>{{ order.date }}</td>
            <td>{{ order.get_status_display }}</td>
            <td>
                {{ order.part_service }}
            </td>
            <td>{{ order.quantity }}</td>
            <td>{{ order.price }}</td>
            <td>
                {% if order.status == 0 %}
                    <a href="{% url 'cancel_order' order.id %}" class="btn btn-danger">{% trans "cancel order"|capfirst %}</a>
                {% elif order.status != 0 and order.status != 3 %}
                    {% trans "this order cannot be cancelled"|capfirst %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>{% trans "No service orders found for this car"|capfirst %}.</p>
{% endif %}
{% endblock content %}

povilo_servisas/autoservisas/templates/autoservisas/user_car_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "my cars from"|title %} {{ block.super }}{% endblock title %}
{% block content %}
<h1>{% trans "my cars"|capfirst %}</h1>
<a href="{% url 'add_car' %}" class="btn btn-primary add-car-button">{% trans "add car"|capfirst %}</a>
{% if car_list %}
    <table class="car-model-table">
        <tr>
            <th>{% trans "model"|capfirst %}</th>
            <th>{% trans "plate"|capfirst %}</th>
            <th>{% trans "vin"|capfirst %}</th>
            <th>{% trans "color"|capfirst %}</th>
            <th>{% trans "action"|capfirst %}</th>
        </tr>
    {% for car in car_list %}
        <tr>
            <td><a href="{% url 'car_service_orders' car.id %}">{{ car.car_model }}</a></td>
            <td>{{ car.plate }}</td>
            <td>{{ car.vin }}</td>
            <td>{{ car.color }}</td>
            <td><a href="{% url 'place_order' car.id %}">{% trans "place order"|capfirst %}</a></td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>{% trans "no cars found"|capfirst %}.</p>
{% endif %}
{% endblock content %}